Foundation-Devices/passport2

ports/stm32/boards/Passport/modules/views/camera.py

Based it to 2.0.4 dev, I'll rebase onto a new dev-v2.0.5 once 2.0.4 is fully released.

PASS1-492: Make camera widget size adaptable.

---

ports/stm32/boards/Passport/modules/flows/backup_flow.py
ports/stm32/boards/Passport/modules/flows/main_flow.py

Prompted the user to backup at every login

Pass1-512: enforce first backup

---

ports/stm32/boards/Passport/modules/flows/connect_wallet_flow.py
ports/stm32/boards/Passport/modules/flows/import_multisig_wallet_from_microsd_flow.py
ports/stm32/boards/Passport/modules/flows/import_multisig_wallet_from_qr_flow.py
ports/stm32/boards/Passport/modules/multisig_wallet.py

I've added error handling for failed multisig imports, and a first pass fix of temporarily removing the passphrase when importing a multisig. I still need to test importing a multisig from microsd and connecting a wallet since I touched those flows, and make sure having a passphrase applied while saving the multisig isn't a problem, but I'd like to start getting feedback on what I have.

Pass1-504: multisig with no keys crash

---

ports/stm32/boards/Passport/modules/ext_settings.py

I realized I had made changes to the wrong settings file, so this resolves problems associated with that.

PASS1-523: carried root_xfp change over to ext_settings

---

ports/stm32/boards/Passport/modules/pages/pin_entry_page.py

I simplified down some if statements that hurt readability. I'm also trying to think of a better name for self.show_security_words to distinguish it from the local update_message(show_security_words). Any ideas @FoundationKen ?

Pass1-510: revise pin entry page

---

CHANGELOG.md
ports/stm32/boards/Passport/modules/multisig_wallet.py

This is a bandaid, since I'm still not sure why removing the code in #83 caused problems.

PASS1-504: bandaided multisig error by reverting some code

---

ports/stm32/Justfile

SFT-1473: bounds check flashing in justfile

---

extmod/foundation/modfoundation.c
lib/lv_bindings/lvgl/src/extra/libs/qrcode/lv_qrcode.c

SFT-2102: Fix signed/unsigned comparisons

---

DEVELOPMENT.md

Fixes documentation issues found in #335.

SFT-2306: Update bootloader build instructions

---

ports/stm32/boards/Passport/modules/flows/sign_psbt_common_flow.py

SFT-2357: transaction details text scrolls founders edition

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md

Adds the appropriate copyright to the bug report issue template.

Fix markdown lint

---

SECURITY/SECURITY.md

This section does not apply to current firmware, though it will be valid in the future. Will re-add once the feature is in place.

Temporarily remove "show seed" section

---

ports/stm32/boards/Passport/modules/flows/import_multisig_wallet_flow.py
ports/stm32/boards/Passport/modules/flows/view_derived_key_details_flow.py
ports/stm32/boards/Passport/modules/flows/view_multisig_details_flow.py
ports/stm32/boards/Passport/modules/menus.py
ports/stm32/boards/Passport/modules/multisig_wallet.py
ports/stm32/boards/Passport/modules/pages/account_details_page.py
ports/stm32/boards/Passport/modules/ui/ui.py
ports/stm32/boards/Passport/modules/utils.py

SFT-2770: using # in account name

---

extmod/foundation-rust/src/ur/encoder.rs
extmod/foundation-rust/src/ur/mod.rs

SFT-2878: maximum density qr code shrinks on fe

---

ports/stm32/boards/Passport/modules/flows/backup_flow.py
ports/stm32/boards/Passport/modules/flows/new_seed_flow.py
ports/stm32/boards/Passport/modules/flows/restore_backup_flow.py
ports/stm32/boards/Passport/modules/flows/restore_seed_flow.py

SFT-3122: made sure initial backup warning only shows during device

---

ports/stm32/boards/Passport/modules/flows/address_explorer_flow.py
ports/stm32/boards/Passport/modules/flows/export_derived_key_flow.py
ports/stm32/boards/Passport/modules/flows/sign_psbt_common_flow.py
ports/stm32/boards/Passport/modules/flows/verify_address_flow.py
ports/stm32/boards/Passport/modules/pages/address_explorer_page.py
ports/stm32/boards/Passport/modules/pages/long_success_page.py
ports/stm32/boards/Passport/modules/pages/long_text_page.py
ports/stm32/boards/Passport/modules/pages/status_page.py
ports/stm32/boards/Passport/modules/pages/success_page.py
ports/stm32/boards/Passport/modules/public_constants.py
ports/stm32/boards/Passport/modules/utils.py

SFT-2887:  final address styling

---

ports/stm32/boards/Passport/modules/flows/address_explorer_flow.py
ports/stm32/boards/Passport/modules/pages/address_type_chooser_page.py
ports/stm32/boards/Passport/modules/pages/singlesig_multisig_chooser_page.py

SFT-3004: change cancel icons to back icons in address explorer

---

ports/stm32/boards/Passport/modules/flows/address_explorer_flow.py

SFT-3223: add receive change option for exploring multisig addresses

---

ports/stm32/boards/Passport/modules/flows/rename_device_flow.py
ports/stm32/boards/Passport/modules/flows/show_security_words_setting_flow.py

SFT-3337: fixed capitalization for security word and device renaming

---

ports/stm32/boards/Passport/modules/flows/scv_flow.py

Reverts Foundation-Devices/passport2#481

Revert "UPDATE: copy on validate url for tampering."

---

ports/stm32/boards/Passport/modules/data_codecs/ur2_codec.py
ports/stm32/boards/Passport/modules/flows/scan_qr_flow.py
ports/stm32/boards/Passport/modules/pages/scan_qr_page.py

SFT-2417: Update upgrade passport message.

---

ports/stm32/boards/Passport/modules/flows/restore_seed_flow.py

…nal word is randomly generated

SFT-3982: remove backup prompts from most temp seed entries

---

ports/stm32/boards/Passport/modules/psbt.py

This was actually an error messaging issue, which this change should improve.

SFT-3980 temporary seeds sticking

---

ports/stm32/boards/Passport/modules/flows/connect_wallet_flow.py

merging into btcpay branch until we determine if it should be included in 2.3.2

SFT-4185: fixed address verification formatting

---

extmod/foundation-rust/embedded-storage-fs/src/lib.rs
extmod/foundation-rust/src/flash.rs

SFT-4402: Implement erase for simulator flash.

---

extmod/foundation-rust/include/foundation.h
extmod/foundation-rust/src/secp256k1.rs
extmod/foundation-rust/src/ur/decoder.rs
extmod/foundation-rust/src/ur/encoder.rs
extmod/foundation-rust/src/ur/mod.rs
extmod/foundation-rust/src/ur/registry.rs
extmod/foundation/modfoundation-secp56k1.h
extmod/foundation/modfoundation-ur.h
ports/stm32/boards/Passport/modules/data_codecs/ur2_codec.py

removed #564 to minimize code changes for 2.3.6

inverted unnecessary changes to dev-v2.3.6
