ports/stm32/boards/Passport/modules/tasks/__init__.py
Should allow QR based BTCPay pairing.
=> PASS1-167: Fix import of generate_addresses_task.

ports/stm32/boards/Passport/modpassport_lv-keypad.h
@FoundationKen suggested that 100ms of cooldown for the same key was too much. 50 ms allows a bit faster pin entry while still preventing most double inputs.
=> PASS1-527: reduced cooldown time to 50 ms

ports/stm32/boards/Passport/modules/files.py, ports/stm32/boards/Passport/modules/flows/export_summary_flow.py
This PR is related to PASS1-526, but I don't want to close that issue since there may be more to it still. For now, this should prevent devices from crashing when having issues mounting SD cards.
=> Bad SD Card Causes Crashes

ports/stm32/boards/Passport/modules/pages/text_input_page.py, ports/stm32/boards/Passport/modules/views/view.py
This memory leak was caused by an item being added to a list every time a special character was selected, and never being removed. I also added a fix for exiting the text_input_page while the symbol_picker was open.
=> Pass1-533: special character passphrases

ports/stm32/boards/Passport/modules/files.py
This allows remounting the SD card when it's unplugged or freshly plugged.
=> PASS1-543: Fix error handling in _try_microsd.

lib/stm32lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sd.c
This is a fix that wasn't carried forward from the FE repo. I'll keep the linear issue open after this for further SD card fixes, because this didn't solve my SD card problems.
=> Pass1-541: improve sd card error handling

ports/stm32/boards/Passport/common/lcd-sharp-ls018b7dh02.c, ports/stm32/boards/Passport/framebuffer.c, ports/stm32/boards/Passport/include/lcd-sharp-ls018b7dh02.h, ports/stm32/boards/Passport/modpassport_lv-lcd.h, ports/stm32/boards/Passport/modules/constants.py, ports/stm32/boards/Passport/modules/display.py, ports/stm32/boards/Passport/modules/pages/scan_qr_page.py, ports/stm32/boards/Passport/modules/views/camera.py
Instead of letting LVGL render pixel-by-pixel from the camera image downsampled to 1 bit-per-pixel, we now render directly to the LCD driver buffer and update just the modified lines.
In addition, the LVGL `_lcd_rounder` callback was always setting the fully display to be updated (in addition to setting `direct_mode=1`, which ended up doing the same thing).  Change it so that only the dirty lines are push to the display.  Also optimized the bit calculation of `_lcd_set_px()` to be a table lookup instead for a small LVGL performance boost.
=> Pass1-576: improve FE screen performance

ports/stm32/boards/Passport/modules/pages/auto_shutdown_setting_page.py, ports/stm32/boards/Passport/modules/pages/brightness_setting_page.py, ports/stm32/boards/Passport/modules/pages/chooser_page.py, ports/stm32/boards/Passport/modules/pages/setting_page.py
Only the AutoShutdownSettingPage needs the special scroll-to-visible fix.  It causes problems on other pages that use the forced scrolling.
=> SFT-1842: Fix ChooserPage item scroll behavior

ports/stm32/boards/Passport/modules/flows/save_to_microsd_flow.py
Folder is properly created now if it does not exist.
=> SFT-2113: Only create backup folder inside CardSlot context

extmod/foundation-rust/Cargo.lock, extmod/foundation-rust/Cargo.toml, extmod/foundation-rust/include/foundation.h, extmod/foundation-rust/src/ur/decoder.rs, extmod/foundation-rust/src/ur/encoder.rs, extmod/foundation-rust/src/ur/mod.rs, extmod/foundation-rust/src/ur/registry.rs
Depends on #341 and Foundation-Devices/foundation-rs#13
=> SFT-2271: Upgrade to foundation-rs

Justfile, REPRODUCIBILITY.md
This allows using Podman to verify the firmware instead of Docker, Podman doesn't require root by default.
=> SFT-2449: Allow to verify the firmware without root.

ports/stm32/Makefile, ports/stm32/main.c, ports/stm32/modmachine.c, ports/stm32/modpyb.c, ports/stm32/moduos.c, ports/stm32/mphalport.c, ports/stm32/stm32_it.c
The USB code was already disabled using the pre-processor, this goes an extra step and removes the compilation support completely.
=> SFT-2860: Remove compilation support for USB stack

ports/stm32/boards/Passport/modules/flows/scv_flow.py
Currently the formatting of the URL doesn't fit on a single line which may confuse the user to misread the full url.  By putting https:// in front of the URL, the user will have a better understanding of where the URL begins.
=> UPDATE: copy on validate url for tampering.

ports/stm32/boards/Passport/modules/flows/scv_flow.py
Currently the formatting of the URL doesn't fit on a single line which may confuse the user to misread the full url. By putting https:// in front of the URL, the user will have a better understanding of where the URL begins.
=> Update: copy on validate url for tampering on scv_flow.py

Dockerfile
* Dockerfile: Install just and cbindgen respecting Cargo.lock.
Fixes #493.
=> SFT-3549: Fix Dockerfile build.

extmod/foundation-rust/Cargo.lock, extmod/foundation-rust/Cargo.toml, extmod/foundation-rust/src/secp256k1.rs
* Cargo.lock: Update lockfile.
* Cargo.toml (dependencies) \<secp256k1\>: Update to 0.29.
* src/secp256k1.rs: Fix breaking changes.
=> SFT-3610: Update rust-secp256k1.

extmod/foundation-rust/Cargo.lock, extmod/foundation-rust/Cargo.toml
* extmod/foundation-rust/Cargo.lock: Regenerate file.
* extmod/foundation-rust/Cargo.toml (dependencies)
\<foundation-ur\>: Update to 0.2.
\<foundation-urtypes\>: Update to 0.3.
\<minicbor\>: Update to 0.24.
=> SFT-3632: Update foundation-urtypes.

extmod/foundation-rust/Cargo.lock, extmod/foundation-rust/Cargo.toml, extmod/foundation-rust/include/foundation.h, extmod/foundation-rust/src/firmware.rs, extmod/foundation-rust/src/lib.rs, extmod/foundation-rust/src/secp256k1.rs, ports/stm32/boards/Passport/manifest.py, ports/stm32/boards/Passport/modpassport-system.h, ports/stm32/boards/Passport/modpassport.c, ports/stm32/boards/Passport/modules/constants.py, ports/stm32/boards/Passport/modules/flows/update_firmware_flow.py, ports/stm32/boards/Passport/modules/tasks/__init__.py, ports/stm32/boards/Passport/modules/tasks/verify_firmware_signature_task.py
This does the same as the bootloader but verifies the image before copying it to check if the user has a corrupt firmware image. The bootloader checked this anyway so this is an extra layer of measure.
=> SFT-3480: Add firmware image signature verification

ports/stm32/Justfile
No private key material is leaked, only the calculated hash that is then verified by the bootloader is printed.
* ports/stm32/Justfile (sign): Pass -d option to cosign.
See CI output for an example.
=> SFT-3854: Enable debug logging when signing firmware.

.github/workflows/build.yaml, ports/stm32/Makefile
* .github/workflows/build.yaml: Upload ELF file with debugging information.
* ports/stm32/Makefile (CFLAGS): Add -g flag.
=> SFT-4381: Enable debug symbols for the firmware.

.github/workflows/build.yaml, .github/workflows/lint.yaml
=> SFT-4382: Bump GitHub actions dependency versions.

extmod/foundation-rust/Cargo.toml
* extmod/foundation-rust/Cargo.toml (profile) <release>: Don't strip debug information.
=> SFT-4385: Don't strip Rust debug information.
